### PR TITLE
Update module paths to use open-policy-agent

### PR DESCRIPTION
**Pull request by tsandall**
This is for https://github.com/open-policy-agent/opa/issues/2387#issuecomment-629102833.

### CODE REVIEW

**Comment by tsandall** [comment]
🌋 📿 let's see what happens!

**Comment by tsandall** [comment]
It's not clear to me from the circle/acceptance.bats output what went wrong though this line seems likely to have caused it: https://github.com/instrumenta/conftest/blob/d58f240b6dd7f88b07592fa4727455dbe999bd13/acceptance.bats#L277

**Comment by jpreese** [comment]
@tsandall the command is trying to pull from https://raw.githubusercontent.com/open-policy-agent/conftest/master/examples/compose/policy/deny.rego which (currently returns a `404`)

```shell
$ conftest test --update https://raw.githubusercontent.com/open-policy-agent/conftest/master/examples/compose/policy/deny.rego examples/compose/docker-compose.yml
```
```
Error: update policies: bad response code: 404
```

This should go away when conftest is actually migrated to the OPA org.

**Comment by jpreese** [comment]
Just so we're not deadlocked on each other, I'm OK to merge this in whenever you want to make the move official!

**Comment by tsandall** [comment]
@jpreese excellent! @garethr when you initiate the repo transfer I can accept it.

**Comment by garethr** [comment]
I've moved the repo. We can merge this and get testing.

**Comment by tsandall** [comment]
I'm going to close and reopen this PR to make sure that DCO is enabled.

**Pull request closed without merging**
