### PR TITLE
[DRAFT] feat(conftest): policy results as github comments and status checks

### PR DESCRIPTION
**Pull request by naiduarvind**
Signed-off-by: Arvind Naidu <arvind.naidu@mindvalley.com>

### CODE REVIEW

**Comment by jpreese** [comment]
Thanks for the pull request, @naiduarvind. Though this feels like it should be added to the Atlantis repository. Maybe as an example custom workflow for integrating policy checks during the plan stage?

**Comment by naiduarvind** [comment]
@jpreese - I understand the confusion you are getting to. The script was initially built for the Atlantis workflow mechanism which later I changed to logics built into a Go binary. However, speaking with @garethr - we wanted to introduce this workflow for Conftest Github Actions as well since this will be a good addition which surfaces visibility for users on how their tests are resulting directly leveraging Github components.

**Comment by naiduarvind** [comment]
I am still working on tweaking this script to work with the Conftest Github Action locally on my repository and tweaking the script to get the flow atleast working. Will update here once the flow is done and we can discuss how this can be introduced into Actions in a better manner if the script introduces overhead.

**Comment by jpreese** [comment]
Oh alright, understood. Looking forward to seeing the completed PR! 👍

**Comment by naiduarvind** [comment]
@jpreese @garethr - got it working. Will push my changes tomorrow and see how we can incorporate it.

**Comment by jpreese** [comment]
Sounds good. Once this is out of `DRAFT` we'll take a look!

**Comment by jpreese** [comment]
Looks like activity has stalled out on this, and @jalseth has created this functionality over at https://github.com/YubicoLabs/action-conftest if we want to route users looking for this functionality there.

**Pull request closed without merging**
