### PR TITLE
Refactor command logic into subpackages for verify and parse commands

### PR DESCRIPTION
**Pull request by Blokje5**
Issue: #316 

This PR is WIP to have a discussion point for the related issue. The idea is to seperate CLI specific logic (Flag parsing, output handling) from the actual logic (Parsing input, Querying Rego). Each command will have an associated Runner. The Runner will be responsible for executing the actual logic, while all CLI specific logic remains inside the command file.

### CODE REVIEW

**Comment by boranx** [comment]
Hi @Blokje5,

The initial(picking `verify` and `parse`) implement is OK for me, 
Thanks for putting this together :+1:  
Having said that, we can consider also unifying some structures in the further like:
```go
configurations, err := parser.GetConfigurations(ctx, input, fileList)
if err != nil {
	return "", fmt.Errorf("calling the parser method: %w", err)
}
```
for `test.go` and `parse.go` or 
moving 
```go
marshal(in interface{}) (string, error)
``` 
to `output.go` for better usability. (Those might be considered refactoring for the future) 
Anyway, from me it lgtm, @jpreese wdyt?

**Comment by Blokje5** [comment]
@boranx yeah I think one of the benefits is that we can inject things like Parsers in a standardised manner in the future. I tried to avoid doing it in this PR as I mostly wanted to outline the structure. I would prefer we do that at a later point in time. As to next steps: I can ensure this PR is no longer in draft (and fix the commit). Then we can merge this PR and work on the other commands individually?

**Comment by boranx** [comment]
Yeah, works for me. Let's get this PR out of "draft" first

**Comment by Blokje5** [comment]
I have updated the PR and removed the draft status. Note that the output related code has been moved to another subpackage. I removed it from internal/commands.

**Comment by Blokje5** [comment]
Also I had to pin the Docker API version in the CircleCI pipeline as I was encountering some issues in the build image step.

**Pull request merged**
