### PR TITLE
fix: Use the right command to pull policies from oci registry

### LINKED ISSUE #919: Error in documentation for pulling OCI registry
The [Sharing doc](https://www.conftest.dev/sharing/) says that for OCI registry a user should do `conftest pull opa.azurecr.io/test` but this is wrong. The right command to use is `conftest pull oci://opa.azurecr.io/test`

### PR DESCRIPTION
**Pull request by gasparev**
Fixes #919

### CODE REVIEW

**Comment by jalseth** [comment]
Is this necessary? The CI attached to this PR works without the `oci://` prefix.

**Comment by gasparev** [comment]
> Is this necessary? The CI attached to this PR works without the `oci://` prefix.

It's needed to pull from the GCP Artifact Registry at least

**Comment by jpreese** [comment]
When using `push` and `pull` the protocol doesn't _have_ to be `oci` so it doesn't feel like putting it in the documentation is the right move. The protocol could also be `https://`, `file://`, etc.

What is an example from pulling from Google Artifact Registry? It may be an issue in how we are detecting the URL, e.g. https://github.com/open-policy-agent/conftest/blob/master/downloader/oci_detector.go#L31

**Comment by gasparev** [comment]
> When using `push` and `pull` the protocol doesn't _have_ to be `oci` so it doesn't feel like putting it in the documentation is the right move. The protocol could also be `https://`, `file://`, etc.
> 
> What is an example from pulling from Google Artifact Registry? It may be an issue in how we are detecting the URL, e.g. https://github.com/open-policy-agent/conftest/blob/master/downloader/oci_detector.go#L31

That explains the issue I see. Host names for Artifact Registry Docker hosts end in `-docker.pkg.dev`.

**Review by jalseth — APPROVED** [review]
Given this change is under an `OCI` heading in the docs, I'm OK with adding this if it means we aren't relying on regex for well-known artifact registries. Thanks for the PR!

**Pull request merged**
