### PR TITLE
Refactor/separate fixtures

### PR DESCRIPTION
**Pull request by xchapter7x**
this is part 1 of this issue:
https://github.com/open-policy-agent/conftest/issues/390

### CODE REVIEW

**Comment by xchapter7x** [comment]
@jpreese / @Blokje5 
Mind taking a peek at this PR?

I copied over only the files in examples which are actually used in the bats and go tests. 
I decided to use the go standard `testdata` directory for those, and left the examples as they are. 

Perhaps in time there will be more package specific testdata fixtures, but for now i've kept them in a single spot. 

The bats acceptance tests in particular make reference to network dependencies in the examples directory. this is for testing the pulling of remote policies from a repository. I've left that as it was. we can change that to something else (when something else exists) or leave it referencing an example file. 

Happy to hear thoughts and feedback... thanks :)

**Comment by jpreese** [comment]
I agree with the idea of splitting up `examples` from `testdata`, but I'm not sure which files _actually_ need to be moved and which could be removed in favor of inline Rego in a Go test. I have a lot of other PRs that touch on tests, and don't necessarily want to cause conflicts when its unknown if the data needs to move.

I planned on going through and combing through the current test suite and making sure that everything is covered appropriately, but my hope is that `testdata` would be incredibly small, maybe not even needed.

**Comment by xchapter7x** [comment]
Fair point.
With regard to which files need to move,
The files in testdata, as part of this PR, are only the files used in the
bats tests. A handful of which were also referenced in go tests, so there
was some overlap there. However, that was minimal.

With your suggestion around using inline rego, do you envision replacing
the bats stuff with a post compile acceptance suite in go?

Let me know how youd like to proceed here. Thanks :)

-John

**Comment by jpreese** [comment]
I think the examples will stay in bats, those have to be files on disk so it makes sense for those to live there.

There might be testdata files that are also used in bats, if the case that were testing doesn't make sense to have the scenario with inline Go. But the objective would be to reduce the reliance on it.

For steps forward, I don't mind just merging this in and we can adjust as we go. Just waiting on the other PRs to see what kind of state the repository is in after that.

**Comment by xchapter7x** [comment]
> For steps forward, I don't mind just merging this in and we can adjust as we go. Just waiting on the other PRs to see what kind of state the repository is in after that.

cool. Let me know when the backlog of PRs is cleared out, and Ill address the resulting merge conflicts. thanks :)

**Pull request closed without merging**
