### PR TITLE
Render trace results once

### PR DESCRIPTION
**Pull request by jpreese**
The overall scope of this PR is to try to provide a better overall `--trace` experience.

Traces are done at the _query_ level, like `data.main.deny` and `data.main.warn`. A query can return multiple results, in the case of multiple deny rules all named the same, but it will still only have a single trace. https://github.com/open-policy-agent/conftest/blob/master/policy/engine.go#L264. 

We're currently associating the same tracelines with every result, causing a lot of extra noise in the rendered results.

This PR introduced a [QueryResult](https://github.com/open-policy-agent/conftest/pull/393/files#diff-37b7a2c0ea3b08b2f425716a910e742aR12) type which puts more emphasis on this idea. Where after the evaluation of a query, what was the query that was executed, what was its result(s), and the associated trace lines. This puts the focus of the trace data around the _query_, and not the result. This also allows us to render traces in a more user-friendly way.

For some bonuses that also came out of this:

- Remove `jsonCheckResult` and `jsonResult` in favor of the package level `CheckResult` and `Result` types. These should both be the same anyway.

- Add `exceptions` to the above types, they were not included in other output formats, such as JSON.

### CODE REVIEW

**Comment by jpreese** [comment]
https://github.com/open-policy-agent/conftest/issues/387

**Review by Blokje5 — CHANGES_REQUESTED** [review]
In general LGTM! It is indeed a really big improvement! 

I tried the output types locally, and I think for table output the results are not really readable. Not sure if that is a deal breaker, but maybe we should just deal with that like you did for junit -> Ignore the traces.

**Comment by jpreese** [comment]
I will do that then! I do agree I'm not really sure there's much value in traces outside of the standard output. I would push for that moreso than trying to make tracing available everywhere.

**Review by Blokje5 — APPROVED** [review]
LGTM! I really like this change!

**Pull request merged**
