### PR TITLE
Update module paths to use open-policy-agent (2nd PR)

### PR DESCRIPTION
**Pull request by tsandall**
This was previously opened in #305 before the repo transfer. I wanted to verify the DCO check so I'm re-opening.

### CODE REVIEW

**Comment by tsandall** [comment]
@garethr it looks like the snyk orb is not allowed to run in until the CircleCI organization settings are updated to allow third-party orbs. Can you update the settings in CircleCI?

**Comment by garethr** [comment]
@tsandall I _think_ that requires an org admin on the GitHub side. For the moment let's remove. I've put up https://github.com/open-policy-agent/conftest/pull/307 if you want to double check. Merging that first should unblock us here.

**Comment by jpreese** [comment]
#307 has been merged.

**Comment by tsandall** [comment]
Looks like @caniszczyk enabled it. I went into circle and updated their org settings as well. Feel free to give it another go.

Screen Shot 2020-05-16 at 4 06 45 PM

**Comment by tsandall** [comment]
Closing and re-opening because for some reason the "re-run job" action in circle is greyed out (when I hover the actions the pointer shows a little 'x' on it.)

Screen Shot 2020-05-16 at 4 09 33 PM

**Comment by tsandall** [comment]
Progress!

Screen Shot 2020-05-16 at 4 11 54 PM

Any ideas?

**Comment by jpreese** [comment]
Navigating to that URL, it looks like it's failing because of the `--update` test again. That CI run does look old though, it says it finished a day ago. As a sanity check, are we sure that execution recent?

I've run the acceptance tests locally and did a scan of the code and everything looks to be in place.

**Comment by garethr** [comment]
Testing locally after merging with master this works for me. Given then I'll merge away. _if_ it still happens in master I'll investigate further 🤞

**Comment by garethr** [comment]
Yup, this passed happily.

One issue I spotted, the CircleCI badge needed updating as well. Fix in https://github.com/open-policy-agent/conftest/pull/308

**Pull request merged**
