### PR TITLE
Added namespace to output

### PR DESCRIPTION
**Pull request by rubelw**

### CODE REVIEW

**Comment by rubelw** [comment]
* Table output
+---------+---------------+-----------------------------+----------------------------------------------+
| RESULT  |     FILE      |          NAMESPACE          |                   MESSAGE                    |
+---------+---------------+-----------------------------+----------------------------------------------+
| failure | ./tfplan.json | namespace1                  | aws_s3_bucket.another_bucket                 |
|         |               |                             | S3 Bucket does not have                      |
|         |               |                             | server-side encryption enabled               |
|         |               |                             |                                              |
| success | ./tfplan.json | namespace2                  | SUCCESS                                      |


* TAP output

# successes
ok 1 - ./tfplan.json - namespace2 - SUCCESS
1..2
not ok 1 - ./tfplan.json - namespace1 - Invalid tags (missing minimum required tags) for the following resources: ["aws_autoscaling_group.my_asg"]

**Review by Blokje5 — CHANGES_REQUESTED** [review]
Overall LGTM! It is a nice improvement and will really help the multiple namespace usecases. However, the JUnit output needs to be updated as well. Maybe it can be included as part of the TestName?

**Comment by rubelw** [comment]
@Blokje5 Update to include namespace in junit output.  Now, junit output will have the namespace appended to the name like so: <testcase classname="conftest" name="./tfplan.json - artifactory_iac_tier_3_2_4" time="0.000"></testcase>

**Review by Blokje5 — APPROVED** [review]
LGTM!

**Pull request merged**
